//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string PublisherName { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Writer { get; set; }
    
        public virtual Publishers Publishers { get; set; }
    }
}
